workspace: 
  src: 'Microsoft Fabric Platform Monitoring'
  trg: 'Microsoft Fabric Platform Monitoring [Test]'

items:
  - Platform and Audit DB.Eventhouse
  - Platform and Audit DB.KQLDatabase
  - CapacityUtilizationEvents.Eventstream
  - GatewayMonitoringHeartbeat.Eventstream
  - GatewayMonitoringReports.Eventstream
  - Monitoring Audit Logs.Notebook
  - Monitoring Extraction Inventory.Notebook
  - Monitoring Extraction Scanner.Notebook
  - Monitoring Extraction Refreshables.Notebook
  - Platform Monitoring.KQLDashboard
