workspace: 
  src: 'Microsoft Fabric Platform Monitoring'
  trg: 'Microsoft Fabric Platform Monitoring [Test]'

items:
  - PlatformMonitoring.Eventhouse
  - PlatformMonitoring.KQLDatabase
  - CapacityUtilizationEvents.Eventstream
  - GatewayMonitoringHeartbeat.Eventstream
  - GatewayMonitoringReports.Eventstream
  - Monitoring Audit Logs.Notebook
  - Monitoring Extraction Inventory.Notebook
  - Monitoring Extraction Scanner.Notebook
